const genUniqueId = (): string => {
  // the unique string is generated by the current date and a random number
  // these values are then converted into a base-36 string using Number.prototype.toString()
  // the value generated by Math.random() is truncated using String.prototype.substring() to select 6 characters
  // the index 2 is used to skip over the decimal point
  // base-36 is also called hexatridecimal, it contains 36 distinct symbols
  // it contains 0-9 as well as a-z
  // for example, 1234 in base-10 can be represented as YA in base-36
  const dateStr = Date.now().toString(36);
  const randomStr = Math.random().toString(36).substring(2, 8);
  return `${dateStr}-${randomStr}`;
};

export default genUniqueId;
